# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - setup_remote_docker
      - heroku/install
      - run: docker login --username=_ --password=$(heroku auth:token) registry.heroku.com
      - run: docker build -t registry.heroku.com/${HEROKU_APP_NAME}/web -f build/Dockerfile .
      - run: docker push registry.heroku.com/${HEROKU_APP_NAME}/web 
      - run: heroku container:release web -a ${HEROKU_APP_NAME}
orbs:
  heroku: circleci/heroku@1.0.1
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - deploy