// Code generated by "stringer -type=State"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Start-0]
	_ = x[Normal-1]
	_ = x[FirstPull-2]
	_ = x[ShouldLay-3]
	_ = x[CanPull-4]
	_ = x[MustLay-5]
	_ = x[NextTurn-6]
}

const _State_name = "StartNormalFirstPullShouldLayCanPullMustLayNextTurn"

var _State_index = [...]uint8{0, 5, 11, 20, 29, 36, 43, 51}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
